spring.application.name=jwt

security.config.prefix=Bearer
security.config.key=MySuperSecretKeyForJwtAuthentication32Chars!
security.config.expiration=3600000

#H2 database connection properties
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:testedb
spring.datasource.username=sa
spring.datasource.password=sa
spring.jpa.show-sql=true
spring.h2.console.enable=true
spring.h2.console.path=/h2-console